
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var k={},n;for(n in f)f.hasOwnProperty(n)&&(k[n]=f[n]);var aa=[],ba="./this.program";function ca(a,b){throw b;}var da="object"===typeof window,v="function"===typeof importScripts,x="",ea,fa,ha,y,z;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)x=v?require("path").dirname(x)+"/":__dirname+"/",ea=function(a,b){y||(y=require("fs"));z||(z=require("path"));a=z.normalize(a);return y.readFileSync(a,b?null:"utf8")},ha=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||A("Assertion failed: undefined");return a},fa=function(a,b,c){y||(y=require("fs"));z||(z=require("path"));a=z.normalize(a);y.readFile(a,function(d,e){d?c(d):b(e.buffer)})},
1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ca=function(a,b){if(noExitRuntime||0<ja)throw process.exitCode=a,b;b instanceof ia||B("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(da||v)v?x=self.location.href:"undefined"!==
typeof document&&document.currentScript&&(x=document.currentScript.src),x=0!==x.indexOf("blob:")?x.substr(0,x.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ka=f.print||console.log.bind(console),B=f.printErr||console.warn.bind(console);for(n in k)k.hasOwnProperty(n)&&(f[n]=k[n]);k=null;f.arguments&&(aa=f.arguments);f.thisProgram&&(ba=f.thisProgram);f.quit&&(ca=f.quit);var C;f.wasmBinary&&(C=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var la,ma=!1;
function na(a){var b=f["_"+a];b||A("Assertion failed: Cannot call unknown function "+(a+", make sure it is exported"));return b}
function oa(a,b,c,d){var e={string:function(q){var r=0;if(null!==q&&void 0!==q&&0!==q){var t=(q.length<<2)+1;r=pa(t);D(q,E,r,t)}return r},array:function(q){var r=pa(q.length);F.set(q,r);return r}};a=na(a);var h=[],g=0;if(d)for(var m=0;m<d.length;m++){var p=e[c[m]];p?(0===g&&(g=qa()),h[m]=p(d[m])):h[m]=d[m]}c=a.apply(null,h);return c=function(q){0!==g&&ra(g);return"string"===b?G(q):"boolean"===b?!!q:q}(c)}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function G(a,b){return a?ta(E,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function va(a){var b=ua(a)+1,c=H(b);c&&D(a,F,c,b);return c}function wa(a){var b=ua(a)+1,c=pa(b);D(a,F,c,b);return c}var F,E,xa,ya,I,za,J,K,Aa,Ba=[],Ca=[],Da=[],Ea=[],Fa=[],ja=0;function Ga(){var a=f.preRun.shift();Ba.unshift(a)}var M=0,Ha=null,Ia=null;f.preloadedImages={};f.preloadedAudios={};
function A(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";B(a);ma=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ja(){return N.startsWith("data:application/octet-stream;base64,")}var N;N="nl.wasm";if(!Ja()){var Ka=N;N=f.locateFile?f.locateFile(Ka,x):x+Ka}function La(){var a=N;try{if(a==N&&C)return new Uint8Array(C);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Ma(){if(!C&&(da||v)){if("function"===typeof fetch&&!N.startsWith("file://"))return fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return La()});if(fa)return new Promise(function(a,b){fa(N,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return La()})}
function Na(){var a=document.getElementById("picker"),b=a.files[0];a.value=null;console.log("--- load file:");console.log("  name: "+b.name);console.log("  type: "+b.type);console.log("  size: "+b.size);256E3>b.size?(a=new FileReader,a.onload=function(c){console.log("file loaded!");(c=c.target.result)?(console.log("content length: "+c.byteLength),c=new Uint8Array(c),0==oa("util_emsc_loadfile","int",["string","array","number"],[b.name,c,c.length])&&console.warn("util_emsc_loadfile() failed!")):console.warn("load result empty!")},
a.readAsArrayBuffer(b)):console.warn("ignoring file because it is too big")}function Oa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Wc;"number"===typeof c?void 0===b.lc?O(c)():O(c)(b.lc):c(void 0===b.lc?null:b.lc)}}}function O(a){return Aa.get(a)}
function Pa(a){this.Zb=a-16;this.Mc=function(b){I[this.Zb+4>>2]=b};this.Jc=function(b){I[this.Zb+8>>2]=b};this.Kc=function(){I[this.Zb>>2]=0};this.Ic=function(){F[this.Zb+12>>0]=0};this.Lc=function(){F[this.Zb+13>>0]=0};this.Fc=function(b,c){this.Mc(b);this.Jc(c);this.Kc();this.Ic();this.Lc()}}var Qa=0,Ra=[null,[],[]],Sa={};function Ta(){void 0===Ta.start&&(Ta.start=Date.now());return 1E3*(Date.now()-Ta.start)|0}var Ua=0;function Va(){for(var a=P.length-1;0<=a;--a)Wa(a);P=[];Xa=[]}var Xa=[];
function Ya(){if(Ua&&Za.cc)for(var a=0;a<Xa.length;++a){var b=Xa[a];Xa.splice(a,1);--a;b.ed.apply(null,b.Sc)}}var P=[];function Wa(a){var b=P[a];b.target.removeEventListener(b.Ub,b.Dc,b.Vb);P.splice(a,1)}function Q(a){function b(d){++Ua;Za=a;Ya();a.Xb(d);Ya();--Ua}if(a.Wb)a.Dc=b,a.target.addEventListener(a.Ub,b,a.Vb),P.push(a),$a||(Ea.push(Va),$a=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].Ub==a.Ub&&Wa(c--)}
function ab(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var $a,Za,bb,cb,db,eb,fb,gb,hb,ib=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function S(a){a=2<a?G(a):a;return ib[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function jb(a){return 0>ib.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function kb(a,b,c,d,e,h){bb||(bb=H(256));a={target:S(a),Ub:h,Wb:d,Xb:function(g){g=g||event;var m=g.target.id?g.target.id:"",p=bb;D(ab(g.target),E,p+0,128);D(m,E,p+128,128);O(d)(e,p,b)&&g.preventDefault()},Vb:c};Q(a)}
function lb(a,b,c,d,e,h){cb||(cb=H(176));a={target:S(a),cc:!0,Ub:h,Wb:d,Xb:function(g){var m=cb;K[m>>3]=g.timeStamp;var p=m>>2;I[p+2]=g.location;I[p+3]=g.ctrlKey;I[p+4]=g.shiftKey;I[p+5]=g.altKey;I[p+6]=g.metaKey;I[p+7]=g.repeat;I[p+8]=g.charCode;I[p+9]=g.keyCode;I[p+10]=g.which;D(g.key||"",E,m+44,32);D(g.code||"",E,m+76,32);D(g.char||"",E,m+108,32);D(g.locale||"",E,m+140,32);O(d)(e,m,b)&&g.preventDefault()},Vb:c};Q(a)}
function mb(a,b,c){K[a>>3]=b.timeStamp;a>>=2;I[a+2]=b.screenX;I[a+3]=b.screenY;I[a+4]=b.clientX;I[a+5]=b.clientY;I[a+6]=b.ctrlKey;I[a+7]=b.shiftKey;I[a+8]=b.altKey;I[a+9]=b.metaKey;xa[2*a+20]=b.button;xa[2*a+21]=b.buttons;I[a+11]=b.movementX;I[a+12]=b.movementY;c=jb(c);I[a+13]=b.clientX-c.left;I[a+14]=b.clientY-c.top}
function nb(a,b,c,d,e,h){db||(db=H(72));a=S(a);Q({target:a,cc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ub:h,Wb:d,Xb:function(g){g=g||event;mb(db,g,a);O(d)(e,db,b)&&g.preventDefault()},Vb:c})}function ob(a,b,c,d,e){eb||(eb=H(260));Q({target:a,Ub:e,Wb:d,Xb:function(h){h=h||event;var g=eb,m=document.pointerLockElement||document.nc||document.pc||document.oc;I[g>>2]=!!m;var p=m&&m.id?m.id:"";D(ab(m),E,g+4,128);D(p,E,g+132,128);O(d)(20,g,b)&&h.preventDefault()},Vb:c})}
function pb(a,b,c,d,e){Q({target:a,Ub:e,Wb:d,Xb:function(h){h=h||event;O(d)(38,0,b)&&h.preventDefault()},Vb:c})}
function qb(a,b,c,d){fb||(fb=H(36));a=S(a);Q({target:a,Ub:"resize",Wb:d,Xb:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=fb;I[g>>2]=e.detail;I[g+4>>2]=h.clientWidth;I[g+8>>2]=h.clientHeight;I[g+12>>2]=innerWidth;I[g+16>>2]=innerHeight;I[g+20>>2]=outerWidth;I[g+24>>2]=outerHeight;I[g+28>>2]=pageXOffset;I[g+32>>2]=pageYOffset;O(d)(10,g,b)&&e.preventDefault()}}},Vb:c})}
function rb(a,b,c,d,e,h){gb||(gb=H(1696));a=S(a);Q({target:a,cc:"touchstart"==h||"touchend"==h,Ub:h,Wb:d,Xb:function(g){for(var m,p={},q=g.touches,r=0;r<q.length;++r)m=q[r],m.sc=m.tc=0,p[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.sc=1,p[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)p[g.targetTouches[r].identifier].tc=1;q=gb;K[q>>3]=g.timeStamp;var t=q>>2;I[t+3]=g.ctrlKey;I[t+4]=g.shiftKey;I[t+5]=g.altKey;I[t+6]=g.metaKey;t+=7;var L=jb(a),l=0;for(r in p)if(m=
p[r],I[t]=m.identifier,I[t+1]=m.screenX,I[t+2]=m.screenY,I[t+3]=m.clientX,I[t+4]=m.clientY,I[t+5]=m.pageX,I[t+6]=m.pageY,I[t+7]=m.sc,I[t+8]=m.tc,I[t+9]=m.clientX-L.left,I[t+10]=m.clientY-L.top,t+=13,31<++l)break;I[q+8>>2]=l;O(d)(e,q,b)&&g.preventDefault()},Vb:c})}function sb(a,b,c,d,e,h){a={target:S(a),Ub:h,Wb:d,Xb:function(g){g=g||event;O(d)(e,0,b)&&g.preventDefault()},Vb:c};Q(a)}
function tb(a,b,c,d){hb||(hb=H(104));Q({target:a,cc:!0,Ub:"wheel",Wb:d,Xb:function(e){e=e||event;var h=hb;mb(h,e,a);K[h+72>>3]=e.deltaX;K[h+80>>3]=e.deltaY;K[h+88>>3]=e.deltaZ;I[h+96>>2]=e.deltaMode;O(d)(9,h,b)&&e.preventDefault()},Vb:c})}
function ub(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function vb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function wb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function xb(a){a.$c=a.getExtension("WEBGL_multi_draw")}
var yb=1,zb=[],T=[],Ab=[],Bb=[],Cb=[],U=[],Db=[],Eb={};function V(a){Fb||(Fb=a)}function Gb(a){for(var b=yb++,c=a.length;c<b;c++)a[c]=null;return b}function Hb(a,b){a.rc||(a.rc=a.getContext,a.getContext=function(d,e){e=a.rc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ib(c,b):0}function Ib(a,b){var c=Gb(Db),d={Yc:c,attributes:b,version:b.Hc,kc:a};a.canvas&&(a.canvas.Rc=d);Db[c]=d;("undefined"===typeof b.qc||b.qc)&&Jb(d);return c}
function Jb(a){a||(a=Kb);if(!a.Gc){a.Gc=!0;var b=a.kc;ub(b);vb(b);wb(b);b.Uc=b.getExtension("EXT_disjoint_timer_query");xb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Fb,Kb,Lb=["default","low-power","high-performance"];function Mb(a,b,c,d){for(var e=0;e<a;e++){var h=W[c](),g=h&&Gb(d);h?(h.name=g,d[g]=h):V(1282);I[b+4*e>>2]=g}}
function Ob(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=W.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=W.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:V(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)I[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V(1280);B("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:V(1280);B("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}I[b>>2]=c}else V(1281)}function Pb(a){var b=ua(a)+1,c=H(b);D(a,E,c,b);return c}
function Qb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function X(a){var b=W.Cc;if(b){var c=b.bc[a];"number"===typeof c&&(b.bc[a]=c=W.getUniformLocation(b,b.Ac[a]+(0<c?"["+c+"]":"")));return c}V(1282)}var Y=[];
function Rb(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?g[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),h=Math.max(b,e);I[Sb()>>2]=60*h;I[Tb()>>2]=Number(b!=e);c=a(c);d=a(d);c=va(c);d=va(d);e<b?(I[Z()>>2]=c,I[Z()+4>>2]=d):(I[Z()>>2]=d,I[Z()+4>>2]=c)}var Ub;function Vb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Wb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Xb=[31,29,31,30,31,30,31,31,30,31,30,31],Yb=[31,28,31,30,31,30,31,31,30,31,30,31];function Zb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Vb(a.getFullYear())?Xb:Yb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}for(var W,$b=new Float32Array(288),ac=0;288>ac;++ac)Y[ac]=$b.subarray(0,ac+1);function bc(a){var b=Array(ua(a)+1);D(a,b,0,b.length);return b}
var gc={p:function(a){return H(a+16)+16},o:function(a,b,c){(new Pa(a)).Fc(b,c);Qa++;throw a;},ca:function(){return 0},ab:function(){return 0},bb:function(){},Za:function(){A("")},jb:Ta,db:function(a,b,c){a=G(a);for(var d="",e=0;e<c;e++)d+=String.fromCharCode(E[b+e]);console.log(btoa(d));b=document.createElement("a");b.setAttribute("href","data:application/octet-stream;base64,"+btoa(d));b.setAttribute("download",a);b.style.display="none";document.body.appendChild(b);b.click();document.body.removeChild(b)},
eb:function(a,b){a=G(a);b=G(b);var c=document.createElement("a");c.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(b));c.setAttribute("download",a);c.style.display="none";document.body.appendChild(c);c.click();document.body.removeChild(c)},gb:function(){f.emsc_js_onload=Na;f.ccall=oa},fb:function(){return navigator.userAgent.includes("Macintosh")?1:0},cb:function(){console.log("$ emsc_js_load");document.getElementById("picker").click()},O:function(){return"number"===typeof devicePixelRatio&&
devicePixelRatio||1},ga:function(a,b,c){a=S(a);if(!a)return-4;a=jb(a);K[b>>3]=a.width;K[c>>3]=a.height;return 0},Xa:function(a,b,c){E.copyWithin(a,b,b+c)},Ga:function(a,b){function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ya:function(){A("OOM")},M:function(a,b,c,d){kb(a,b,c,d,12,"blur");return 0},J:function(a,b,c){a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},N:function(a,b,c,d){kb(a,b,c,d,13,"focus");return 0},X:function(a,b,c,d){lb(a,b,c,d,2,"keydown");return 0},
V:function(a,b,c,d){lb(a,b,c,d,1,"keypress");return 0},W:function(a,b,c,d){lb(a,b,c,d,3,"keyup");return 0},ba:function(a,b,c,d){nb(a,b,c,d,5,"mousedown");return 0},_:function(a,b,c,d){nb(a,b,c,d,33,"mouseenter");return 0},Z:function(a,b,c,d){nb(a,b,c,d,34,"mouseleave");return 0},$:function(a,b,c,d){nb(a,b,c,d,8,"mousemove");return 0},aa:function(a,b,c,d){nb(a,b,c,d,6,"mouseup");return 0},Q:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.nc||document.body.pc||
document.body.oc))return-1;a=S(a);if(!a)return-4;ob(a,b,c,d,"pointerlockchange");ob(a,b,c,d,"mozpointerlockchange");ob(a,b,c,d,"webkitpointerlockchange");ob(a,b,c,d,"mspointerlockchange");return 0},P:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.nc||document.body.pc||document.body.oc))return-1;a=S(a);if(!a)return-4;pb(a,b,c,d,"pointerlockerror");pb(a,b,c,d,"mozpointerlockerror");pb(a,b,c,d,"webkitpointerlockerror");pb(a,b,c,d,"mspointerlockerror");return 0},Ua:function(a,
b,c,d){qb(a,b,c,d);return 0},R:function(a,b,c,d){rb(a,b,c,d,25,"touchcancel");return 0},S:function(a,b,c,d){rb(a,b,c,d,23,"touchend");return 0},T:function(a,b,c,d){rb(a,b,c,d,24,"touchmove");return 0},U:function(a,b,c,d){rb(a,b,c,d,22,"touchstart");return 0},L:function(a,b,c,d){sb(a,b,c,d,31,"webglcontextlost");return 0},K:function(a,b,c,d){sb(a,b,c,d,32,"webglcontextrestored");return 0},Y:function(a,b,c,d){a=S(a);return"undefined"!==typeof a.onwheel?(tb(a,b,c,d),0):-1},fa:function(a,b){b>>=2;b={alpha:!!I[b],
depth:!!I[b+1],stencil:!!I[b+2],antialias:!!I[b+3],premultipliedAlpha:!!I[b+4],preserveDrawingBuffer:!!I[b+5],powerPreference:Lb[I[b+6]],failIfMajorPerformanceCaveat:!!I[b+7],Hc:I[b+8],Zc:I[b+9],qc:I[b+10],Ec:I[b+11],ad:I[b+12],bd:I[b+13]};a=S(a);return!a||b.Ec?0:Hb(a,b)},Va:function(a,b){a=Db[a];b=G(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&ub(W);"OES_vertex_array_object"==b&&vb(W);"WEBGL_draw_buffers"==b&&wb(W);"WEBGL_multi_draw"==b&&xb(W);return!!a.kc.getExtension(b)},
nb:function(a){a>>=2;for(var b=0;14>b;++b)I[a+b]=0;I[a]=I[a+1]=I[a+3]=I[a+4]=I[a+8]=I[a+10]=1},_a:function(a){Kb=Db[a];f.Tc=W=Kb&&Kb.kc;return!a||W?0:-5},ea:function(){return 0},$a:function(a,b,c,d){a=Sa.Xc(a);b=Sa.Vc(a,b,c);I[d>>2]=b;return 0},Wa:function(){},da:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var g=I[b>>2],m=I[b+4>>2];b+=8;for(var p=0;p<m;p++){var q=E[g+p],r=Ra[a];0===q||10===q?((1===a?ka:B)(ta(r,0)),r.length=0):r.push(q)}e+=m}I[d>>2]=e;return 0},H:function(a){W.activeTexture(a)},x:function(a,
b){W.attachShader(T[a],U[b])},f:function(a,b){W.bindBuffer(a,zb[b])},s:function(a,b){W.bindFramebuffer(a,Ab[b])},ya:function(a,b){W.bindRenderbuffer(a,Bb[b])},e:function(a,b){W.bindTexture(a,Cb[b])},C:function(a,b,c,d){W.blendColor(a,b,c,d)},D:function(a,b){W.blendEquationSeparate(a,b)},E:function(a,b,c,d){W.blendFuncSeparate(a,b,c,d)},Aa:function(a,b,c,d){W.bufferData(a,c?E.subarray(c,c+b):b,d)},y:function(a,b,c,d){W.bufferSubData(a,b,E.subarray(d,d+c))},xb:function(a){W.clear(a)},ja:function(a,
b,c,d){W.clearColor(a,b,c,d)},ia:function(a){W.clearDepth(a)},ha:function(a){W.clearStencil(a)},g:function(a,b,c,d){W.colorMask(!!a,!!b,!!c,!!d)},ma:function(a){W.compileShader(U[a])},va:function(a,b,c,d,e,h,g,m){W.compressedTexImage2D(a,b,c,d,e,h,m?E.subarray(m,m+g):null)},sa:function(){var a=Gb(T),b=W.createProgram();b.name=a;b.fc=b.dc=b.ec=0;b.mc=1;T[a]=b;return a},oa:function(a){var b=Gb(U);U[b]=W.createShader(a);return b},z:function(a){W.cullFace(a)},Ia:function(a,b){for(var c=0;c<a;c++){var d=
I[b+4*c>>2],e=zb[d];e&&(W.deleteBuffer(e),e.name=0,zb[d]=null)}},m:function(a,b){for(var c=0;c<a;++c){var d=I[b+4*c>>2],e=Ab[d];e&&(W.deleteFramebuffer(e),e.name=0,Ab[d]=null)}},G:function(a){if(a){var b=T[a];b?(W.deleteProgram(b),b.name=0,T[a]=null):V(1281)}},I:function(a,b){for(var c=0;c<a;c++){var d=I[b+4*c>>2],e=Bb[d];e&&(W.deleteRenderbuffer(e),e.name=0,Bb[d]=null)}},i:function(a){if(a){var b=U[a];b?(W.deleteShader(b),U[a]=null):V(1281)}},Ha:function(a,b){for(var c=0;c<a;c++){var d=I[b+4*c>>
2],e=Cb[d];e&&(W.deleteTexture(e),e.name=0,Cb[d]=null)}},l:function(a){W.depthFunc(a)},k:function(a){W.depthMask(!!a)},a:function(a){W.disable(a)},F:function(a){W.disableVertexAttribArray(a)},kb:function(a,b,c){W.drawArrays(a,b,c)},lb:function(a,b,c,d){W.drawElements(a,b,c,d)},c:function(a){W.enable(a)},sb:function(a){W.enableVertexAttribArray(a)},A:function(a){W.frontFace(a)},Ba:function(a,b){Mb(a,b,"createBuffer",zb)},za:function(a,b){Mb(a,b,"createRenderbuffer",Bb)},wa:function(a,b){Mb(a,b,"createTexture",
Cb)},ka:function(a,b){return W.getAttribLocation(T[a],G(b))},b:function(a,b){Ob(a,b)},qa:function(a,b,c,d){a=W.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(I[c>>2]=b)},w:function(a,b,c){if(c)if(a>=yb)V(1281);else if(a=T[a],35716==b)a=W.getProgramInfoLog(a),null===a&&(a="(unknown error)"),I[c>>2]=a.length+1;else if(35719==b){if(!a.fc)for(b=0;b<W.getProgramParameter(a,35718);++b)a.fc=Math.max(a.fc,W.getActiveUniform(a,b).name.length+1);I[c>>2]=a.fc}else if(35722==
b){if(!a.dc)for(b=0;b<W.getProgramParameter(a,35721);++b)a.dc=Math.max(a.dc,W.getActiveAttrib(a,b).name.length+1);I[c>>2]=a.dc}else if(35381==b){if(!a.ec)for(b=0;b<W.getProgramParameter(a,35382);++b)a.ec=Math.max(a.ec,W.getActiveUniformBlockName(a,b).length+1);I[c>>2]=a.ec}else I[c>>2]=W.getProgramParameter(a,b);else V(1281)},la:function(a,b,c,d){a=W.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(I[c>>2]=b)},t:function(a,b,c){c?35716==b?(a=W.getShaderInfoLog(U[a]),
null===a&&(a="(unknown error)"),I[c>>2]=a?a.length+1:0):35720==b?(a=W.getShaderSource(U[a]),I[c>>2]=a?a.length+1:0):I[c>>2]=W.getShaderParameter(U[a],b):V(1281)},Ja:function(a){var b=Eb[a];if(!b){switch(a){case 7939:b=W.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Pb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=W.getParameter(a))||V(1280);b=b&&Pb(b);break;case 7938:b=Pb("OpenGL ES 2.0 ("+W.getParameter(7938)+")");break;case 35724:b=W.getParameter(35724);
var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Pb(b);break;default:V(1280)}Eb[a]=b}return b},v:function(a,b){b=G(b);if(a=T[a]){var c=a,d=c.bc,e=c.Bc,h;if(!d)for(c.bc=d={},c.Ac={},h=0;h<W.getProgramParameter(c,35718);++h){var g=W.getActiveUniform(c,h);var m=g.name;g=g.size;var p=Qb(m);p=0<p?m.slice(0,p):m;var q=c.mc;c.mc+=g;e[p]=[g,q];for(m=0;m<g;++m)d[q]=m,c.Ac[q++]=p}c=a.bc;d=0;e=b;h=Qb(b);0<h&&(d=parseInt(b.slice(h+
1))>>>0,e=b.slice(0,h));if((e=a.Bc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||W.getUniformLocation(a,b)))return d}else V(1281);return-1},ra:function(a){a=T[a];W.linkProgram(a);a.bc=0;a.Bc={}},B:function(a,b){W.polygonOffset(a,b)},xa:function(a,b,c,d){W.renderbufferStorage(a,b,c,d)},q:function(a,b,c,d){W.scissor(a,b,c,d)},na:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?I[d+4*h>>2]:-1;e+=G(I[c+4*h>>2],0>g?void 0:g)}W.shaderSource(U[a],e)},Ea:function(a,b,c){W.stencilFunc(a,b,c)},wb:function(a,b,c,d){W.stencilFuncSeparate(a,
b,c,d)},j:function(a){W.stencilMask(a)},Da:function(a,b,c){W.stencilOp(a,b,c)},vb:function(a,b,c,d){W.stencilOpSeparate(a,b,c,d)},ua:function(a,b,c,d,e,h,g,m,p){var q=W,r=q.texImage2D;if(p){var t=m-5120;t=1==t?E:4==t?I:6==t?J:5==t||28922==t?za:ya;var L=31-Math.clz32(t.BYTES_PER_ELEMENT);p=t.subarray(p>>L,p+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<L)+4-1&-4)>>L)}else p=null;r.call(q,a,b,c,d,e,h,g,m,p)},d:function(a,b,c){W.texParameteri(a,b,c)},rb:function(a,b,c){if(288>=b)for(var d=Y[b-
1],e=0;e<b;++e)d[e]=J[c+4*e>>2];else d=J.subarray(c>>2,c+4*b>>2);W.uniform1fv(X(a),d)},pa:function(a,b){W.uniform1i(X(a),b)},qb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=J[c+4*e>>2],d[e+1]=J[c+(4*e+4)>>2];else d=J.subarray(c>>2,c+8*b>>2);W.uniform2fv(X(a),d)},pb:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=J[c+4*e>>2],d[e+1]=J[c+(4*e+4)>>2],d[e+2]=J[c+(4*e+8)>>2];else d=J.subarray(c>>2,c+12*b>>2);W.uniform3fv(X(a),d)},ob:function(a,b,c){if(72>=b){var d=Y[4*
b-1],e=J;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=J.subarray(c>>2,c+16*b>>2);W.uniform4fv(X(a),d)},mb:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],h=J;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=J.subarray(d>>
2,d+64*b>>2);W.uniformMatrix4fv(X(a),!!c,e)},h:function(a){a=T[a];W.useProgram(a);W.Cc=a},tb:function(a,b){W.vertexAttribDivisor(a,b)},ub:function(a,b,c,d,e,h){W.vertexAttribPointer(a,b,c,!!d,e,h)},r:function(a,b,c,d){W.viewport(a,b,c,d)},ib:function(a,b){Ub||(Ub=!0,Rb());a=new Date(1E3*I[a>>2]);I[b>>2]=a.getSeconds();I[b+4>>2]=a.getMinutes();I[b+8>>2]=a.getHours();I[b+12>>2]=a.getDate();I[b+16>>2]=a.getMonth();I[b+20>>2]=a.getFullYear()-1900;I[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,
1);I[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;I[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;I[b+32>>2]=a;a=I[Z()+(a?4:0)>>2];I[b+40>>2]=a;return b},Ta:function(){f.uc=function(a){0!=cc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.uc)},Sa:function(){f.zc=function(a){a=a.clipboardData.getData("text");oa("_sapp_emsc_onpaste","void",["string"],
[a])};window.addEventListener("paste",f.zc)},Ra:function(a){f.cd=[];a=G(a);a=document.getElementById(a);f.vc=function(b){b.stopPropagation();b.preventDefault()};f.wc=function(b){b.stopPropagation();b.preventDefault()};f.xc=function(b){b.stopPropagation();b.preventDefault()};f.yc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.dd=c;dc(c.length);var d;for(d=0;d<c.length;d++)oa("_sapp_emsc_drop","void",["number","string"],[d,c[d].name]);ec(b.clientX,b.clientY)};a.addEventListener("dragenter",
f.vc,!1);a.addEventListener("dragleave",f.wc,!1);a.addEventListener("dragover",f.xc,!1);a.addEventListener("drop",f.yc,!1)},Ca:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Pa:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){fc()});document.body.append(a)},Oa:function(){document.getElementById("_sokol_app_input_element").focus()},zb:function(a){a=
G(a);f.$b=document.getElementById(a);f.$b||console.log("sokol_app.h: invalid target:"+a);f.$b.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ma:function(){window.removeEventListener("beforeunload",f.uc)},La:function(){window.removeEventListener("paste",f.zc)},Ka:function(a){a=G(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.vc);a.removeEventListener("dragleave",f.wc);a.removeEventListener("dragover",f.xc);a.removeEventListener("drop",
f.yc)},Qa:function(){f.$b&&f.$b.requestPointerLock&&f.$b.requestPointerLock()},ta:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(E.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Na:function(){document.getElementById("_sokol_app_input_element").blur()},Fa:function(a){a=G(a);var b=document.createElement("textarea");
b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},yb:function(){return navigator.userAgent.includes("Macintosh")?1:0},u:function(){return performance.now()},hb:function(a,b,c,d){function e(l,u,w){for(l="number"===typeof l?
l.toString():l||"";l.length<u;)l=w[0]+l;return l}function h(l,u){return e(l,u,"0")}function g(l,u){function w(Nb){return 0>Nb?-1:0<Nb?1:0}var R;0===(R=w(l.getFullYear()-u.getFullYear()))&&0===(R=w(l.getMonth()-u.getMonth()))&&(R=w(l.getDate()-u.getDate()));return R}function m(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-
1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function p(l){l=Zb(new Date(l.Tb+1900,0,1),l.jc);var u=new Date(l.getFullYear()+1,0,4),w=m(new Date(l.getFullYear(),0,4));u=m(u);return 0>=g(w,l)?0>=g(u,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var q=I[d+40>>2];d={Pc:I[d>>2],Oc:I[d+4>>2],hc:I[d+8>>2],ac:I[d+12>>2],Yb:I[d+16>>2],Tb:I[d+20>>2],ic:I[d+24>>2],jc:I[d+28>>2],gd:I[d+32>>2],Nc:I[d+36>>2],Qc:q?G(q):""};c=G(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d",
"%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),L="January February March April May June July August September October November December".split(" ");
q={"%a":function(l){return t[l.ic].substring(0,3)},"%A":function(l){return t[l.ic]},"%b":function(l){return L[l.Yb].substring(0,3)},"%B":function(l){return L[l.Yb]},"%C":function(l){return h((l.Tb+1900)/100|0,2)},"%d":function(l){return h(l.ac,2)},"%e":function(l){return e(l.ac,2," ")},"%g":function(l){return p(l).toString().substring(2)},"%G":function(l){return p(l)},"%H":function(l){return h(l.hc,2)},"%I":function(l){l=l.hc;0==l?l=12:12<l&&(l-=12);return h(l,2)},"%j":function(l){return h(l.ac+Wb(Vb(l.Tb+
1900)?Xb:Yb,l.Yb-1),3)},"%m":function(l){return h(l.Yb+1,2)},"%M":function(l){return h(l.Oc,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.hc&&12>l.hc?"AM":"PM"},"%S":function(l){return h(l.Pc,2)},"%t":function(){return"\t"},"%u":function(l){return l.ic||7},"%U":function(l){var u=new Date(l.Tb+1900,0,1),w=0===u.getDay()?u:Zb(u,7-u.getDay());l=new Date(l.Tb+1900,l.Yb,l.ac);return 0>g(w,l)?h(Math.ceil((31-w.getDate()+(Wb(Vb(l.getFullYear())?Xb:Yb,l.getMonth()-1)-31)+l.getDate())/7),2):
0===g(w,u)?"01":"00"},"%V":function(l){var u=new Date(l.Tb+1901,0,4),w=m(new Date(l.Tb+1900,0,4));u=m(u);var R=Zb(new Date(l.Tb+1900,0,1),l.jc);return 0>g(R,w)?"53":0>=g(u,R)?"01":h(Math.ceil((w.getFullYear()<l.Tb+1900?l.jc+32-w.getDate():l.jc+1-w.getDate())/7),2)},"%w":function(l){return l.ic},"%W":function(l){var u=new Date(l.Tb,0,1),w=1===u.getDay()?u:Zb(u,0===u.getDay()?1:7-u.getDay()+1);l=new Date(l.Tb+1900,l.Yb,l.ac);return 0>g(w,l)?h(Math.ceil((31-w.getDate()+(Wb(Vb(l.getFullYear())?Xb:Yb,
l.getMonth()-1)-31)+l.getDate())/7),2):0===g(w,u)?"01":"00"},"%y":function(l){return(l.Tb+1900).toString().substring(2)},"%Y":function(l){return l.Tb+1900},"%z":function(l){l=l.Nc;var u=0<=l;l=Math.abs(l)/60;return(u?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.Qc},"%%":function(){return"%"}};for(r in q)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));r=bc(c);if(r.length>b)return 0;F.set(r,a);return r.length-1},n:function(a){var b=Date.now()/1E3|0;a&&(I[a>>2]=
b);return b}};
(function(){function a(e){f.asm=e.exports;la=f.asm.Ab;e=la.buffer;f.HEAP8=F=new Int8Array(e);f.HEAP16=xa=new Int16Array(e);f.HEAP32=I=new Int32Array(e);f.HEAPU8=E=new Uint8Array(e);f.HEAPU16=ya=new Uint16Array(e);f.HEAPU32=za=new Uint32Array(e);f.HEAPF32=J=new Float32Array(e);f.HEAPF64=K=new Float64Array(e);Aa=f.asm.Cb;Ca.unshift(f.asm.Bb);M--;f.monitorRunDependencies&&f.monitorRunDependencies(M);0==M&&(null!==Ha&&(clearInterval(Ha),Ha=null),Ia&&(e=Ia,Ia=null,e()))}function b(e){a(e.instance)}function c(e){return Ma().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(e,function(h){B("failed to asynchronously prepare wasm: "+h);A(h)})}var d={a:gc};M++;f.monitorRunDependencies&&f.monitorRunDependencies(M);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return B("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return C||"function"!==typeof WebAssembly.instantiateStreaming||Ja()||N.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(h){B("wasm streaming compile failed: "+h);B("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Bb).apply(null,arguments)};var fc=f.__sapp_emsc_notify_keyboard_hidden=function(){return(fc=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Db).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.Eb).apply(null,arguments)};
var cc=f.__sapp_html5_get_ask_leave_site=function(){return(cc=f.__sapp_html5_get_ask_leave_site=f.asm.Fb).apply(null,arguments)},dc=f.__sapp_emsc_begin_drop=function(){return(dc=f.__sapp_emsc_begin_drop=f.asm.Gb).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.Hb).apply(null,arguments)};var ec=f.__sapp_emsc_end_drop=function(){return(ec=f.__sapp_emsc_end_drop=f.asm.Ib).apply(null,arguments)};
f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Jb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Kb).apply(null,arguments)};var H=f._malloc=function(){return(H=f._malloc=f.asm.Lb).apply(null,arguments)};f._util_emsc_loadfile=function(){return(f._util_emsc_loadfile=f.asm.Mb).apply(null,arguments)};
var Z=f.__get_tzname=function(){return(Z=f.__get_tzname=f.asm.Nb).apply(null,arguments)},Tb=f.__get_daylight=function(){return(Tb=f.__get_daylight=f.asm.Ob).apply(null,arguments)},Sb=f.__get_timezone=function(){return(Sb=f.__get_timezone=f.asm.Pb).apply(null,arguments)},qa=f.stackSave=function(){return(qa=f.stackSave=f.asm.Qb).apply(null,arguments)},ra=f.stackRestore=function(){return(ra=f.stackRestore=f.asm.Rb).apply(null,arguments)},pa=f.stackAlloc=function(){return(pa=f.stackAlloc=f.asm.Sb).apply(null,
arguments)},hc;function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ia=function ic(){hc||jc();hc||(Ia=ic)};
function jc(a){function b(){if(!hc&&(hc=!0,f.calledRun=!0,!ma)){Oa(Ca);Oa(Da);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(kc){var c=a,d=f._main;c=c||[];var e=c.length+1,h=pa(4*(e+1));I[h>>2]=wa(ba);for(var g=1;g<e;g++)I[(h>>2)+g]=wa(c[g-1]);I[(h>>2)+e]=0;try{var m=d(e,h);if(!(noExitRuntime||0<ja)){if(f.onExit)f.onExit(m);ma=!0}ca(m,new ia(m))}catch(p){p instanceof ia||"unwind"==p||ca(1,p)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=
f.postRun.shift(),Fa.unshift(c);Oa(Fa)}}a=a||aa;if(!(0<M)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ga();Oa(Ba);0<M||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=jc;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var kc=!0;f.noInitialRun&&(kc=!1);jc();
