
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in f)f.hasOwnProperty(l)&&(k[l]=f[l]);var aa=[],ba="./this.program";function t(a,b){throw b;}var ca="object"===typeof window,u="function"===typeof importScripts,v="",da,w,ea,x,y;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)v=u?require("path").dirname(v)+"/":__dirname+"/",da=function(a,b){x||(x=require("fs"));y||(y=require("path"));a=y.normalize(a);return x.readFileSync(a,b?null:"utf8")},ea=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||z("Assertion failed: undefined");return a},w=function(a,b,c){x||(x=require("fs"));y||(y=require("path"));a=y.normalize(a);x.readFile(a,function(d,e){d?c(d):b(e.buffer)})},
1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;}),process.on("unhandledRejection",function(a){throw a;}),t=function(a,b){if(noExitRuntime||0<ha)throw process.exitCode=a,b;b instanceof fa||A("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ca||u)u?v=self.location.href:"undefined"!==
typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),w=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(f[l]=k[l]);k=null;f.arguments&&(aa=f.arguments);f.thisProgram&&(ba=f.thisProgram);f.quit&&(t=f.quit);var B;f.wasmBinary&&(B=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var ja,ka=!1;
function la(a){var b=f["_"+a];b||z("Assertion failed: Cannot call unknown function "+(a+", make sure it is exported"));return b}
function ma(a,b,c,d){var e={string:function(p){var r=0;if(null!==p&&void 0!==p&&0!==p){var q=(p.length<<2)+1;r=C(q);D(p,E,r,q)}return r},array:function(p){var r=C(p.length);F.set(p,r);return r}};a=la(a);var h=[],g=0;if(d)for(var m=0;m<d.length;m++){var n=e[c[m]];n?(0===g&&(g=na()),h[m]=n(d[m])):h[m]=d[m]}c=a.apply(null,h);return c=function(p){0!==g&&oa(g);return"string"===b?G(p):"boolean"===b?!!p:p}(c)}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function G(a,b){return a?qa(E,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function sa(a){var b=ra(a)+1,c=C(b);D(a,F,c,b);return c}var F,E,ta,ua,H,va,I,J,wa,xa=[],ya=[],za=[],Aa=[],Ba=[],ha=0;function Ca(){var a=f.preRun.shift();xa.unshift(a)}var K=0,Da=null,L=null;f.preloadedImages={};f.preloadedAudios={};
function z(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";A(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ea(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="nl.wasm";if(!Ea()){var Fa=M;M=f.locateFile?f.locateFile(Fa,v):v+Fa}function Ga(){var a=M;try{if(a==M&&B)return new Uint8Array(B);if(ea)return ea(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ha(){if(!B&&(ca||u)){if("function"===typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ga()});if(w)return new Promise(function(a,b){w(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ga()})}
function Ia(){var a=document.getElementById("picker"),b=a.files[0];a.value=null;console.log("--- load file:");console.log("  name: "+b.name);console.log("  type: "+b.type);console.log("  size: "+b.size);256E3>b.size?(a=new FileReader,a.onload=function(c){console.log("file loaded!");(c=c.target.result)?(console.log("content length: "+c.byteLength),c=new Uint8Array(c),0==ma("util_emsc_loadfile","int",["string","array","number"],[b.name,c,c.length])&&console.warn("util_emsc_loadfile() failed!")):console.warn("load result empty!")},
a.readAsArrayBuffer(b)):console.warn("ignoring file because it is too big")}function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Gc;"number"===typeof c?void 0===b.Zb?N(c)():N(c)(b.Zb):c(void 0===b.Zb?null:b.Zb)}}}function N(a){return wa.get(a)}
function Ka(a){this.Rb=a-16;this.Ac=function(b){H[this.Rb+4>>2]=b};this.xc=function(b){H[this.Rb+8>>2]=b};this.yc=function(){H[this.Rb>>2]=0};this.wc=function(){F[this.Rb+12>>0]=0};this.zc=function(){F[this.Rb+13>>0]=0};this.tc=function(b,c){this.Ac(b);this.xc(c);this.yc();this.wc();this.zc()}}var La=0,Ma=[null,[],[]],Na={};function Oa(){void 0===Oa.start&&(Oa.start=Date.now());return 1E3*(Date.now()-Oa.start)|0}var Pa=0;function Qa(){for(var a=P.length-1;0<=a;--a)Ra(a);P=[];Sa=[]}var Sa=[];
function Ta(){if(Pa&&Ua.Ub)for(var a=0;a<Sa.length;++a){var b=Sa[a];Sa.splice(a,1);--a;b.Pc.apply(null,b.Cc)}}var P=[];function Ra(a){var b=P[a];b.target.removeEventListener(b.Nb,b.rc,b.Ob);P.splice(a,1)}function Q(a){function b(d){++Pa;Ua=a;Ta();a.Qb(d);Ta();--Pa}if(a.Pb)a.rc=b,a.target.addEventListener(a.Nb,b,a.Ob),P.push(a),Va||(Aa.push(Qa),Va=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].Nb==a.Nb&&Ra(c--)}
function Wa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Va,Ua,Xa,Ya,Za,$a,ab,bb,cb,db=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function R(a){a=2<a?G(a):a;return db[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function eb(a){return 0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function fb(a,b,c,d,e,h){Xa||(Xa=S(256));a={target:R(a),Nb:h,Pb:d,Qb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Xa;D(Wa(g.target),E,n+0,128);D(m,E,n+128,128);N(d)(e,n,b)&&g.preventDefault()},Ob:c};Q(a)}
function gb(a,b,c,d,e,h){Ya||(Ya=S(176));a={target:R(a),Ub:!0,Nb:h,Pb:d,Qb:function(g){var m=Ya;J[m>>3]=g.timeStamp;var n=m>>2;H[n+2]=g.location;H[n+3]=g.ctrlKey;H[n+4]=g.shiftKey;H[n+5]=g.altKey;H[n+6]=g.metaKey;H[n+7]=g.repeat;H[n+8]=g.charCode;H[n+9]=g.keyCode;H[n+10]=g.which;D(g.key||"",E,m+44,32);D(g.code||"",E,m+76,32);D(g.char||"",E,m+108,32);D(g.locale||"",E,m+140,32);N(d)(e,m,b)&&g.preventDefault()},Ob:c};Q(a)}
function hb(a,b,c){J[a>>3]=b.timeStamp;a>>=2;H[a+2]=b.screenX;H[a+3]=b.screenY;H[a+4]=b.clientX;H[a+5]=b.clientY;H[a+6]=b.ctrlKey;H[a+7]=b.shiftKey;H[a+8]=b.altKey;H[a+9]=b.metaKey;ta[2*a+20]=b.button;ta[2*a+21]=b.buttons;H[a+11]=b.movementX;H[a+12]=b.movementY;c=eb(c);H[a+13]=b.clientX-c.left;H[a+14]=b.clientY-c.top}
function T(a,b,c,d,e,h){Za||(Za=S(72));a=R(a);Q({target:a,Ub:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Nb:h,Pb:d,Qb:function(g){g=g||event;hb(Za,g,a);N(d)(e,Za,b)&&g.preventDefault()},Ob:c})}function ib(a,b,c,d,e){$a||($a=S(260));Q({target:a,Nb:e,Pb:d,Qb:function(h){h=h||event;var g=$a,m=document.pointerLockElement||document.ac||document.cc||document.bc;H[g>>2]=!!m;var n=m&&m.id?m.id:"";D(Wa(m),E,g+4,128);D(n,E,g+132,128);N(d)(20,g,b)&&h.preventDefault()},Ob:c})}
function jb(a,b,c,d,e){Q({target:a,Nb:e,Pb:d,Qb:function(h){h=h||event;N(d)(38,0,b)&&h.preventDefault()},Ob:c})}
function kb(a,b,c,d){ab||(ab=S(36));a=R(a);Q({target:a,Nb:"resize",Pb:d,Qb:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=ab;H[g>>2]=e.detail;H[g+4>>2]=h.clientWidth;H[g+8>>2]=h.clientHeight;H[g+12>>2]=innerWidth;H[g+16>>2]=innerHeight;H[g+20>>2]=outerWidth;H[g+24>>2]=outerHeight;H[g+28>>2]=pageXOffset;H[g+32>>2]=pageYOffset;N(d)(10,g,b)&&e.preventDefault()}}},Ob:c})}
function lb(a,b,c,d,e,h){bb||(bb=S(1696));a=R(a);Q({target:a,Ub:"touchstart"==h||"touchend"==h,Nb:h,Pb:d,Qb:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.fc=m.hc=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.fc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].hc=1;p=bb;J[p>>3]=g.timeStamp;var q=p>>2;H[q+3]=g.ctrlKey;H[q+4]=g.shiftKey;H[q+5]=g.altKey;H[q+6]=g.metaKey;q+=7;var O=eb(a),mb=0;for(r in n)if(m=
n[r],H[q]=m.identifier,H[q+1]=m.screenX,H[q+2]=m.screenY,H[q+3]=m.clientX,H[q+4]=m.clientY,H[q+5]=m.pageX,H[q+6]=m.pageY,H[q+7]=m.fc,H[q+8]=m.hc,H[q+9]=m.clientX-O.left,H[q+10]=m.clientY-O.top,q+=13,31<++mb)break;H[p+8>>2]=mb;N(d)(e,p,b)&&g.preventDefault()},Ob:c})}function nb(a,b,c,d,e,h){a={target:R(a),Nb:h,Pb:d,Qb:function(g){g=g||event;N(d)(e,0,b)&&g.preventDefault()},Ob:c};Q(a)}
function ob(a,b,c,d){cb||(cb=S(104));Q({target:a,Ub:!0,Nb:"wheel",Pb:d,Qb:function(e){e=e||event;var h=cb;hb(h,e,a);J[h+72>>3]=e.deltaX;J[h+80>>3]=e.deltaY;J[h+88>>3]=e.deltaZ;H[h+96>>2]=e.deltaMode;N(d)(9,h,b)&&e.preventDefault()},Ob:c})}
function pb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function qb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function rb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function sb(a){a.Kc=a.getExtension("WEBGL_multi_draw")}
var tb=1,ub=[],U=[],vb=[],wb=[],xb=[],V=[],yb=[],zb={};function W(a){Ab||(Ab=a)}function Bb(a){for(var b=tb++,c=a.length;c<b;c++)a[c]=null;return b}function Cb(a,b){a.ec||(a.ec=a.getContext,a.getContext=function(d,e){e=a.ec(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Db(c,b):0}function Db(a,b){var c=Bb(yb),d={Ic:c,attributes:b,version:b.vc,Yb:a};a.canvas&&(a.canvas.Bc=d);yb[c]=d;("undefined"===typeof b.dc||b.dc)&&Eb(d);return c}
function Eb(a){a||(a=Fb);if(!a.uc){a.uc=!0;var b=a.Yb;pb(b);qb(b);rb(b);b.Ec=b.getExtension("EXT_disjoint_timer_query");sb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Ab,Fb,Gb=["default","low-power","high-performance"];function Hb(a,b,c,d){for(var e=0;e<a;e++){var h=X[c](),g=h&&Bb(d);h?(h.name=g,d[g]=h):W(1282);H[b+4*e>>2]=g}}
function Ib(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)H[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:W(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}H[b>>2]=c}else W(1281)}function Jb(a){var b=ra(a)+1,c=S(b);D(a,E,c,b);return c}
function Kb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Y(a){var b=X.qc;if(b){var c=b.Tb[a];"number"===typeof c&&(b.Tb[a]=c=X.getUniformLocation(b,b.oc[a]+(0<c?"["+c+"]":"")));return c}W(1282)}for(var Z=[],X,Lb=new Float32Array(288),Mb=0;288>Mb;++Mb)Z[Mb]=Lb.subarray(0,Mb+1);
var Rb={o:function(a){return S(a+16)+16},n:function(a,b,c){(new Ka(a)).tc(b,c);La++;throw a;},ba:function(){return 0},$a:function(){return 0},ab:function(){},Za:function(){z("")},gb:Oa,cb:function(a,b){a=G(a);b=G(b);var c=document.createElement("a");c.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(b));c.setAttribute("download",a);c.style.display="none";document.body.appendChild(c);c.click();document.body.removeChild(c)},eb:function(){f.emsc_js_onload=Ia;f.ccall=ma},db:function(){return navigator.userAgent.includes("Macintosh")?
1:0},bb:function(){console.log("$$$ emsc_js_load");document.getElementById("picker").click()},N:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},fa:function(a,b,c){a=R(a);if(!a)return-4;a=eb(a);J[b>>3]=a.width;J[c>>3]=a.height;return 0},Xa:function(a,b,c){E.copyWithin(a,b,b+c)},Fa:function(a,b){function c(d){N(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ya:function(){z("OOM")},L:function(a,b,c,d){fb(a,b,c,d,12,"blur");return 0},I:function(a,b,c){a=R(a);
if(!a)return-4;a.width=b;a.height=c;return 0},M:function(a,b,c,d){fb(a,b,c,d,13,"focus");return 0},W:function(a,b,c,d){gb(a,b,c,d,2,"keydown");return 0},U:function(a,b,c,d){gb(a,b,c,d,1,"keypress");return 0},V:function(a,b,c,d){gb(a,b,c,d,3,"keyup");return 0},aa:function(a,b,c,d){T(a,b,c,d,5,"mousedown");return 0},Z:function(a,b,c,d){T(a,b,c,d,33,"mouseenter");return 0},Y:function(a,b,c,d){T(a,b,c,d,34,"mouseleave");return 0},_:function(a,b,c,d){T(a,b,c,d,8,"mousemove");return 0},$:function(a,b,c,
d){T(a,b,c,d,6,"mouseup");return 0},P:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ac||document.body.cc||document.body.bc))return-1;a=R(a);if(!a)return-4;ib(a,b,c,d,"pointerlockchange");ib(a,b,c,d,"mozpointerlockchange");ib(a,b,c,d,"webkitpointerlockchange");ib(a,b,c,d,"mspointerlockchange");return 0},O:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.ac||document.body.cc||document.body.bc))return-1;a=R(a);if(!a)return-4;
jb(a,b,c,d,"pointerlockerror");jb(a,b,c,d,"mozpointerlockerror");jb(a,b,c,d,"webkitpointerlockerror");jb(a,b,c,d,"mspointerlockerror");return 0},Ta:function(a,b,c,d){kb(a,b,c,d);return 0},Q:function(a,b,c,d){lb(a,b,c,d,25,"touchcancel");return 0},R:function(a,b,c,d){lb(a,b,c,d,23,"touchend");return 0},S:function(a,b,c,d){lb(a,b,c,d,24,"touchmove");return 0},T:function(a,b,c,d){lb(a,b,c,d,22,"touchstart");return 0},K:function(a,b,c,d){nb(a,b,c,d,31,"webglcontextlost");return 0},J:function(a,b,c,d){nb(a,
b,c,d,32,"webglcontextrestored");return 0},X:function(a,b,c,d){a=R(a);return"undefined"!==typeof a.onwheel?(ob(a,b,c,d),0):-1},ea:function(a,b){b>>=2;b={alpha:!!H[b],depth:!!H[b+1],stencil:!!H[b+2],antialias:!!H[b+3],premultipliedAlpha:!!H[b+4],preserveDrawingBuffer:!!H[b+5],powerPreference:Gb[H[b+6]],failIfMajorPerformanceCaveat:!!H[b+7],vc:H[b+8],Jc:H[b+9],dc:H[b+10],sc:H[b+11],Lc:H[b+12],Mc:H[b+13]};a=R(a);return!a||b.sc?0:Cb(a,b)},Ua:function(a,b){a=yb[a];b=G(b);b.startsWith("GL_")&&(b=b.substr(3));
"ANGLE_instanced_arrays"==b&&pb(X);"OES_vertex_array_object"==b&&qb(X);"WEBGL_draw_buffers"==b&&rb(X);"WEBGL_multi_draw"==b&&sb(X);return!!a.Yb.getExtension(b)},kb:function(a){a>>=2;for(var b=0;14>b;++b)H[a+b]=0;H[a]=H[a+1]=H[a+3]=H[a+4]=H[a+8]=H[a+10]=1},Wa:function(a){Fb=yb[a];f.Dc=X=Fb&&Fb.Yb;return!a||X?0:-5},da:function(){return 0},_a:function(a,b,c,d){a=Na.Hc(a);b=Na.Fc(a,b,c);H[d>>2]=b;return 0},Va:function(){},ca:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var g=H[b>>2],m=H[b+4>>2];b+=8;for(var n=
0;n<m;n++){var p=E[g+n],r=Ma[a];0===p||10===p?((1===a?ia:A)(qa(r,0)),r.length=0):r.push(p)}e+=m}H[d>>2]=e;return 0},G:function(a){X.activeTexture(a)},w:function(a,b){X.attachShader(U[a],V[b])},f:function(a,b){X.bindBuffer(a,ub[b])},r:function(a,b){X.bindFramebuffer(a,vb[b])},xa:function(a,b){X.bindRenderbuffer(a,wb[b])},e:function(a,b){X.bindTexture(a,xb[b])},B:function(a,b,c,d){X.blendColor(a,b,c,d)},C:function(a,b){X.blendEquationSeparate(a,b)},D:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},
za:function(a,b,c,d){X.bufferData(a,c?E.subarray(c,c+b):b,d)},x:function(a,b,c,d){X.bufferSubData(a,b,E.subarray(d,d+c))},ub:function(a){X.clear(a)},ia:function(a,b,c,d){X.clearColor(a,b,c,d)},ha:function(a){X.clearDepth(a)},ga:function(a){X.clearStencil(a)},g:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},la:function(a){X.compileShader(V[a])},ua:function(a,b,c,d,e,h,g,m){X.compressedTexImage2D(a,b,c,d,e,h,m?E.subarray(m,m+g):null)},ra:function(){var a=Bb(U),b=X.createProgram();b.name=a;b.Xb=b.Vb=
b.Wb=0;b.$b=1;U[a]=b;return a},na:function(a){var b=Bb(V);V[b]=X.createShader(a);return b},y:function(a){X.cullFace(a)},Ha:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=ub[d];e&&(X.deleteBuffer(e),e.name=0,ub[d]=null)}},m:function(a,b){for(var c=0;c<a;++c){var d=H[b+4*c>>2],e=vb[d];e&&(X.deleteFramebuffer(e),e.name=0,vb[d]=null)}},F:function(a){if(a){var b=U[a];b?(X.deleteProgram(b),b.name=0,U[a]=null):W(1281)}},H:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=wb[d];e&&(X.deleteRenderbuffer(e),
e.name=0,wb[d]=null)}},i:function(a){if(a){var b=V[a];b?(X.deleteShader(b),V[a]=null):W(1281)}},Ga:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],e=xb[d];e&&(X.deleteTexture(e),e.name=0,xb[d]=null)}},l:function(a){X.depthFunc(a)},k:function(a){X.depthMask(!!a)},a:function(a){X.disable(a)},E:function(a){X.disableVertexAttribArray(a)},hb:function(a,b,c){X.drawArrays(a,b,c)},ib:function(a,b,c,d){X.drawElements(a,b,c,d)},c:function(a){X.enable(a)},pb:function(a){X.enableVertexAttribArray(a)},z:function(a){X.frontFace(a)},
Aa:function(a,b){Hb(a,b,"createBuffer",ub)},ya:function(a,b){Hb(a,b,"createRenderbuffer",wb)},va:function(a,b){Hb(a,b,"createTexture",xb)},ja:function(a,b){return X.getAttribLocation(U[a],G(b))},b:function(a,b){Ib(a,b)},pa:function(a,b,c,d){a=X.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(H[c>>2]=b)},v:function(a,b,c){if(c)if(a>=tb)W(1281);else if(a=U[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==b){if(!a.Xb)for(b=
0;b<X.getProgramParameter(a,35718);++b)a.Xb=Math.max(a.Xb,X.getActiveUniform(a,b).name.length+1);H[c>>2]=a.Xb}else if(35722==b){if(!a.Vb)for(b=0;b<X.getProgramParameter(a,35721);++b)a.Vb=Math.max(a.Vb,X.getActiveAttrib(a,b).name.length+1);H[c>>2]=a.Vb}else if(35381==b){if(!a.Wb)for(b=0;b<X.getProgramParameter(a,35382);++b)a.Wb=Math.max(a.Wb,X.getActiveUniformBlockName(a,b).length+1);H[c>>2]=a.Wb}else H[c>>2]=X.getProgramParameter(a,b);else W(1281)},ka:function(a,b,c,d){a=X.getShaderInfoLog(V[a]);
null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(H[c>>2]=b)},s:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),H[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(V[a]),H[c>>2]=a?a.length+1:0):H[c>>2]=X.getShaderParameter(V[a],b):W(1281)},Ia:function(a){var b=zb[a];if(!b){switch(a){case 7939:b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Jb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||
W(1280);b=b&&Jb(b);break;case 7938:b=Jb("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Jb(b);break;default:W(1280)}zb[a]=b}return b},u:function(a,b){b=G(b);if(a=U[a]){var c=a,d=c.Tb,e=c.pc,h;if(!d)for(c.Tb=d={},c.oc={},h=0;h<X.getProgramParameter(c,35718);++h){var g=X.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Kb(m);
n=0<n?m.slice(0,n):m;var p=c.$b;c.$b+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.oc[p++]=n}c=a.Tb;d=0;e=b;h=Kb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.pc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else W(1281);return-1},qa:function(a){a=U[a];X.linkProgram(a);a.Tb=0;a.pc={}},A:function(a,b){X.polygonOffset(a,b)},wa:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},p:function(a,b,c,d){X.scissor(a,b,c,d)},ma:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=
d?H[d+4*h>>2]:-1;e+=G(H[c+4*h>>2],0>g?void 0:g)}X.shaderSource(V[a],e)},Da:function(a,b,c){X.stencilFunc(a,b,c)},tb:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},j:function(a){X.stencilMask(a)},Ca:function(a,b,c){X.stencilOp(a,b,c)},sb:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},ta:function(a,b,c,d,e,h,g,m,n){var p=X,r=p.texImage2D;if(n){var q=m-5120;q=1==q?E:4==q?H:6==q?I:5==q||28922==q?va:ua;var O=31-Math.clz32(q.BYTES_PER_ELEMENT);n=q.subarray(n>>O,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-
6402]||1)*(1<<O)+4-1&-4)>>O)}else n=null;r.call(p,a,b,c,d,e,h,g,m,n)},d:function(a,b,c){X.texParameteri(a,b,c)},ob:function(a,b,c){if(288>=b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=I[c+4*e>>2];else d=I.subarray(c>>2,c+4*b>>2);X.uniform1fv(Y(a),d)},oa:function(a,b){X.uniform1i(Y(a),b)},nb:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=I[c+4*e>>2],d[e+1]=I[c+(4*e+4)>>2];else d=I.subarray(c>>2,c+8*b>>2);X.uniform2fv(Y(a),d)},mb:function(a,b,c){if(96>=b)for(var d=Z[3*b-1],e=0;e<3*b;e+=3)d[e]=
I[c+4*e>>2],d[e+1]=I[c+(4*e+4)>>2],d[e+2]=I[c+(4*e+8)>>2];else d=I.subarray(c>>2,c+12*b>>2);X.uniform3fv(Y(a),d)},lb:function(a,b,c){if(72>=b){var d=Z[4*b-1],e=I;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=I.subarray(c>>2,c+16*b>>2);X.uniform4fv(Y(a),d)},jb:function(a,b,c,d){if(18>=b){var e=Z[16*b-1],h=I;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+
7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=I.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(Y(a),!!c,e)},h:function(a){a=U[a];X.useProgram(a);X.qc=a},qb:function(a,b){X.vertexAttribDivisor(a,b)},rb:function(a,b,c,d,e,h){X.vertexAttribPointer(a,b,c,!!d,e,h)},q:function(a,b,c,d){X.viewport(a,b,c,d)},Sa:function(){f.ic=function(a){0!=Nb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",
f.ic)},Ra:function(){f.nc=function(a){a=a.clipboardData.getData("text");ma("_sapp_emsc_onpaste","void",["string"],[a])};window.addEventListener("paste",f.nc)},Qa:function(a){f.Nc=[];a=G(a);a=document.getElementById(a);f.jc=function(b){b.stopPropagation();b.preventDefault()};f.kc=function(b){b.stopPropagation();b.preventDefault()};f.lc=function(b){b.stopPropagation();b.preventDefault()};f.mc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.Oc=c;Ob(c.length);var d;for(d=
0;d<c.length;d++)ma("_sapp_emsc_drop","void",["number","string"],[d,c[d].name]);Pb(b.clientX,b.clientY)};a.addEventListener("dragenter",f.jc,!1);a.addEventListener("dragleave",f.kc,!1);a.addEventListener("dragover",f.lc,!1);a.addEventListener("drop",f.mc,!1)},Ba:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Oa:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",
function(){Qb()});document.body.append(a)},Na:function(){document.getElementById("_sokol_app_input_element").focus()},wb:function(a){a=G(a);f.Sb=document.getElementById(a);f.Sb||console.log("sokol_app.h: invalid target:"+a);f.Sb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},La:function(){window.removeEventListener("beforeunload",f.ic)},Ka:function(){window.removeEventListener("paste",f.nc)},Ja:function(a){a=G(a);a=document.getElementById(a);a.removeEventListener("dragenter",
f.jc);a.removeEventListener("dragleave",f.kc);a.removeEventListener("dragover",f.lc);a.removeEventListener("drop",f.mc)},Pa:function(){f.Sb&&f.Sb.requestPointerLock&&f.Sb.requestPointerLock()},sa:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(E.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},
Ma:function(){document.getElementById("_sokol_app_input_element").blur()},Ea:function(a){a=G(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},vb:function(){return navigator.userAgent.includes("Macintosh")?
1:0},t:function(){return performance.now()},fb:function(a){var b=Date.now()/1E3|0;a&&(H[a>>2]=b);return b}};
(function(){function a(e){f.asm=e.exports;ja=f.asm.xb;e=ja.buffer;f.HEAP8=F=new Int8Array(e);f.HEAP16=ta=new Int16Array(e);f.HEAP32=H=new Int32Array(e);f.HEAPU8=E=new Uint8Array(e);f.HEAPU16=ua=new Uint16Array(e);f.HEAPU32=va=new Uint32Array(e);f.HEAPF32=I=new Float32Array(e);f.HEAPF64=J=new Float64Array(e);wa=f.asm.zb;ya.unshift(f.asm.yb);K--;f.monitorRunDependencies&&f.monitorRunDependencies(K);0==K&&(null!==Da&&(clearInterval(Da),Da=null),L&&(e=L,L=null,e()))}function b(e){a(e.instance)}function c(e){return Ha().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(e,function(h){A("failed to asynchronously prepare wasm: "+h);z(h)})}var d={a:Rb};K++;f.monitorRunDependencies&&f.monitorRunDependencies(K);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Ea()||M.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(h){A("wasm streaming compile failed: "+h);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.yb).apply(null,arguments)};var Qb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Qb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Ab).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.Bb).apply(null,arguments)};
var Nb=f.__sapp_html5_get_ask_leave_site=function(){return(Nb=f.__sapp_html5_get_ask_leave_site=f.asm.Cb).apply(null,arguments)},Ob=f.__sapp_emsc_begin_drop=function(){return(Ob=f.__sapp_emsc_begin_drop=f.asm.Db).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.Eb).apply(null,arguments)};var Pb=f.__sapp_emsc_end_drop=function(){return(Pb=f.__sapp_emsc_end_drop=f.asm.Fb).apply(null,arguments)};
f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Gb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Hb).apply(null,arguments)};var S=f._malloc=function(){return(S=f._malloc=f.asm.Ib).apply(null,arguments)};f._util_emsc_loadfile=function(){return(f._util_emsc_loadfile=f.asm.Jb).apply(null,arguments)};
var na=f.stackSave=function(){return(na=f.stackSave=f.asm.Kb).apply(null,arguments)},oa=f.stackRestore=function(){return(oa=f.stackRestore=f.asm.Lb).apply(null,arguments)},C=f.stackAlloc=function(){return(C=f.stackAlloc=f.asm.Mb).apply(null,arguments)},Sb;function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Tb(){Sb||Ub();Sb||(L=Tb)};
function Ub(a){function b(){if(!Sb&&(Sb=!0,f.calledRun=!0,!ka)){Ja(ya);Ja(za);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Vb){var c=a,d=f._main;c=c||[];var e=c.length+1,h=C(4*(e+1));H[h>>2]=sa(ba);for(var g=1;g<e;g++)H[(h>>2)+g]=sa(c[g-1]);H[(h>>2)+e]=0;try{var m=d(e,h);if(!(noExitRuntime||0<ha)){if(f.onExit)f.onExit(m);ka=!0}t(m,new fa(m))}catch(n){n instanceof fa||"unwind"==n||t(1,n)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),
Ba.unshift(c);Ja(Ba)}}a=a||aa;if(!(0<K)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ca();Ja(xa);0<K||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Ub;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Vb=!0;f.noInitialRun&&(Vb=!1);Ub();
